# Generated by Django 5.2 on 2025-04-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
